### ISSUE TITLE
Fetching standards "embedded" in other standards

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iec#21]
```
[relaton-iec] ("IEC 60050-311") fetching...
[relaton-iec] WARNING: no match found online for IEC 60050-311:2001. The code must be exactly like it is on the standards website.
[relaton-iec] The provided document part may not exist, or the document may no longer be published in parts.
```

This is not found because the standard is being sold in a "package" under IEC 60050-300.

https://webstore.iec.ch/publication/192
<img width="745" alt="Screen Shot 2020-04-08 at 1 14 09 PM" src="https://user-images.githubusercontent.com/11865/78746988-d5f8d380-799a-11ea-9e9f-03dca8900ea7.png">

Tricky...

**Comment by andrew2net** [comment]
@ronaldtse so when we search `IEC 60050-311` reference then we should get document `IEC 60050-300:2001`, right?

**Comment by ronaldtse** [comment]
@andrew2net correct.
