### ISSUE TITLE
Provide urn for every IEC document according to IEC URN scheme

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iec#22]
We want to provide URN information for IEC documents as per the attached.

Rules | Examples | URN
-- | -- | --
If any field is absent, leave empty |   | urn:iec:std:iec:60601-1-1:::: vs urn:iec:std:iec:60601-1-1:2005-10:tr:prv:fr
All URIs are extensible, to - define adjuncts (such as amendment, corrigendum or interpretation sheet). - name consolidations (such as base edition plus its amendment)The adjunct string is appended to the base URI (after \|\| or _) |   |  
  | Naming an adjunct (e.g. corrigendum to an amendment): | urn:iec:std:iec:60601-1-1:2015-10:::\|\|amd:1:2017-01\|\|cor:1:2018-01
  | Consolidation of base edition and its amendments: | urn:iec:std:iec:60601-1-1:2015-04:csv:_amd:1:2016-07_amd:2:2017-02
All values in lower-case |   |  
  |   |  
Separation between a base document and its adjuncts: When a base edition is amended, corrected or otherwise added to, the URN is constructed using that of the base edition, to which we add information on the adjunct. Two types of reference exist: either to the adjunct itself or to the consolidation of the base edition with one or more of its adjuncts.The base edition information is separated from the adjunct information by three fields. The middle field indicates whether the reference is to a consolidation or not. If left empty, the reference is to the adjunct itself. If it contains the word "plus", it is a consolidation. |   |  
  | Amendment 1:1993 to IEC 60068-2-2:1974 | urn:iec:std:iec:60068-2-2:1974: : : : :amd:1:1993
  | Consolidation of amendment 1:1993 with IEC 60068-2-2:1974 | urn:iec:std:iec:60068-2-2:1974: : : :plus:amd:1:1993
Note on adjuncts: In theory, there is no limit to the number of adjuncts that are possible. In practice, when there are many adjuncts, it is advisable to either make use of an undated reference to the base edition as a whole, or to deliver content by different means, such as database standards.
  |   |  
Separator and Rule |   |  
":" Between fields in the URN |   | urn:iec:std:iec:60601
"-" Within field |   | urn:iec:std:iec-iso:60601-1-1:
"#" Between URI and IDs for document elements, such as clauses, figures, etc. |   | urn:iec:std:iec:60601-1-1:2015-10:::#fig-1  (the Component ID specifications is TBD)
  |   |  
Note on IDs: The IDs content elements used in this document and its examples are those that were used in IEC's conversion process. Outside the context of conversion excercises, the use of semantic ID naming schemes is not necessarily encouraged. This URN model can be used with other IDs.
Note on languages: Languages are listed in alphabetical order, to ensure that identical values are expressed in the same way (and at the same time, to avoid complex tables of language combinations to solve the problem)

P.S. related to https://github.com/relaton/relaton-iso/issues/85

**Comment by ronaldtse** [comment]
prefix |   |   |   |   |   | base document information |   |   |   |   |   |   |   |   |   |   |   |   |   | adjunct document information |   |   |   |   | component or related asset information |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
urn | : | sdo namespace | : | content type namespace | : | header | : | project number | : | date | : | type | : | deliverable | : | language |   |   |   | adjunct type | : | adjunct number | : | date | # or = | component id or related asset
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | : | relation | : |   |   |   |   |   |   |  
urn | : | iec | : | std | : | iec | : | 67654 | : | blank | : | blank | : | prv | : | blank | : | plus | : | amd | : | 1 | : | 2010-08 | # | fig-1
urn | : |   | : |   | : | iso | : | 60601-1 | : | 2010-03 | : | ts | : | csv | : | en | : |   | : | amd | : | 1 | : | 2010-12 | # | sec-1
urn | : |   | : |   | : | iec-iso | : | 61076-7-101 | : | 2010 | : | tr | : | exv | : | fr | : | plus | : | cor | : | etc… | : | 2010-11 | # | sec-3.4
urn | : |   | : |   | : | iec-ieee | : | 80004 | : | 2010-10-11 | : | pas | : | rlv | : | ru | : | plus | : | ish | : | 1 | : | etc. | # | sec-4.5.6
urn | : |   | : |   | : | iec-itu | : | etc. | : |   | : | guide | : | cmv | : | en-fr | : | plus | : | … | : |   | : |   | # | tabl-7
urn | : |   | : |   | : | iec-astm | : |   | : |   | : | is | : |   | : | en-fr-ru | : | plus | : |   | : |   | : |   | # | anx-a
urn |   |   |   |   |   |   |   |   |   |   |   | ser |   |   |   |   |   |   |   |   |   |   |   |   | # | not-4.6.7-2
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | # | nte-3.2-1
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | # | etc.
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | = | software supplement
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | = | voting report
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | = | webpage
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | = | forum

**Comment by ronaldtse** [comment]
| Prefix |   |   |   |   |   | Base document information |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | Component or related asset information |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Example source | URN | : | namespace SDO | : | namespace Type | : | Header | : | Project number | : | Date | : | Type | : | Deliverable | : | Language | : | Relation | : | Adjunct type | : | Adjunct number | : | Date | : | Relation | : |   |   |   |   |   | # or = | Component ID or Related asset
IEC 60445 | urn | : | iec | : | std | : | iec | : | 60445 | : |   | : |   | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
IEC 61076 series | urn | : | iec | : | std | : | iec | : | 61076 | : |   | : | ser | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
IEC 61076-7 series | urn | : | iec | : | std | : | iec | : | 61076-7 | : |   | : | ser | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
IEC 60065:2001 | urn | : | iec | : | std | : | iec | : | 60065 | : | 2001 | : |   | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   | # |  
IEC 60065:2001 adopted by another org XYZ | urn | : | xyz | : | std | : | iec | : | 60065 | : | 2001 | : |   | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   | # |  
CISPR 11:2015-06 | urn | : | iec | : | std | : | cispr | : | 11 | : | 2015-06 | : |   | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
Amendment 1:1993 to IEC 60068-2-2:1974 | urn | : | iec | : | std | : | iec | : | 60068-2-2 | : | 1974 | : |   | : |   | : |   | : |   | : | amd | : | 1 | : | 1993 | : |   | : |   |   |   |   |   |   |  
Consolidation of amendment 1:1993 with IEC 60068-2-2:1974 | urn | : | iec | : | std | : | iec | : | 60068-2-2 | : | 1974 | : |   | : | csv | : |   | : | plus | : | amd | : | 1 | : | 1993 | : |   | : |   |   |   |   |   |   |  
Amendment 1:1993 to IEC 60068-2-2:1974 | urn | : | iec | : | std | : | iec | : | 60068-2-2 | : | 1974 | : |   | : |   | : |   | : |   | : | amd | : | 1 | : | 1993 | : |   | : |   |   |   |   |   |   |  
Amendment 2:1994 to IEC 60068-2-2:1975 | urn | : | iec | : | std | : | iec | : | 60068-2-2 | : | 1974 | : |   | : |   | : |   | : |   | : | amd | : | 2 | : | 1994 | : |   | : |   |   |   |   |   |   |  
Corrigendum 1:2001 to Amendment 2:1994 to IEC 60068-2-2:1976 | urn | : | iec | : | std | : | iec | : | 60068-2-2 | : | 1974-01 | : |   | : |   | : |   | : |   | : | amd | : | 2 | : | 1994-05 | : |   | : | cor | : | 1 | : | 2001-01 |   |  
Consolidation of IEC 60027-1:1992, its Amendment 1:1997 and its Amendment 2:2005 | urn | : | iec | : | std | : | iec | : | 60027-1 | : | 1992 | : |   | : | csv | : |   | : | plus | : | amd | : | 1 | : | 1997 | : | plus | : | amd | : | 2 | : | 2005 |   |  
Amendment 1:2017 to IEC 60601-2-63:2012 | urn | : | iec | : | std | : | iec | : | 60601-2-63 | : | 2012 | : |   | : |   | : |   | : |   | : | amd | : | 1 | : | 2017-03-01 | : |   | : |   |   |   |   |   |   |  
Prerelease version of IEC 60601-2-63:2012/Amendment 1:2017 | urn | : | iec | : | std | : | iec | : | 60601-2-63 | : | 2012 | : |   | : | prv | : |   | : |   | : | amd | : | 1 | : | 2017-03-01 | : |   | : |   |   |   |   |   |   |  
ISO 14971:2000 | urn | : | iec | : | std | : | iso | : | 14971 | : | 2000 | : |   | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
ISO/IEC 11801 | urn | : | iec | : | std | : | iso-iec | : | 11801 | : |   | : |   | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
ISO/IEC TR 11802-9901:2014 | urn | : | iec | : | std | : | iso-iec | : | 11802-9901 | : | 2014 | : | tr | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
IEC/PAS 62825 | urn | : | iec | : | std | : | iec | : | 62825 | : |   | : | pas | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
IEC GUIDE 111:2004-07 | urn | : | iec | : | std | : | iec | : | 111 | : | 2004-07 | : | guide | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
IEC 60068-2-2:1974 | urn | : | iec | : | std | : | iec | : | 60068-2-2 | : | 1974 | : |   | : |   | : |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
IEC 60068-2-2:1974 in french | urn | : | iec | : | std | : | iec | : | 60068-2-2 | : | 1974 | : |   | : |   | : | fr | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | : |   | : |   |   |   |   |   | : |   | : |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Reference to entire database (same as other documents): |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Reference to entire database (undated) | urn | : | iec | : | std | : | iec | : | 60417 | : |   | : |   | : |   | : |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Reference to entire database (dated) | urn | : | iec | : | std | : | iec | : | 60417 | : | 2010-10 | : |   | : |   | : |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Reference to single database entries. A distinction is made between those released as part of a set (e.g. a part of the IEV) and those which are released individually: |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
One database entry with its own date of release (e.g. graphical symbol) | urn | : | iec | : | std | : | iec | : | 60417-5012 | : | 2010-10 | : |   | : |   | : |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
One database entry with its own date of release (e.g. terminological entry in the IEV) | urn | : | iec | : | std | : | iec | : | 60050-121-10-34 | : | 2016-11 | : |   | : |   | : |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
One database entry within a dated set of entries (e.g. terminological entry in a part of the IEV) | urn | : | iec | : | std | : | iec | : | 60050-121 | : | 2010-10 | : |   | : |   | : |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | # | con-121-10-23

**Comment by andrew2net** [comment]
> |       |       |
> | --- | --- |
> |  type | For IS: can be blank or use "is". Other currently existing values: ts, tr, pas, guide, is, srd, ser (for series/all parts) |

I noticed here https://webstore.iec.ch/searchform what the SER is in a same group with CSV and PRV, so supposed it's a Deliverable, not Type.

**Comment by ronaldtse** [comment]
Thanks @andrew2net ! could you help document this method so others can directly use it too, via API and command line? Thanks.
