### ISSUE TITLE
Scraping: support all existing IEC stage codes

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iec#27]
This list of stage codes is obtained from:

https://www.iec.ch/dyn/www/f?p=103:20:0

<img width="783" alt="Screen Shot 2020-12-04 at 4 19 14 PM" src="https://user-images.githubusercontent.com/11865/101139402-77304a80-364c-11eb-9aef-84b3c40d32e7.png">

Some of these codes are retired or special. For example, "SPE" stands for "Special" which is given as a placeholder for "database standards" projects, because they are continuous projects that do not end.

I believe relaton-iec needs to support all of these codes in the model (and scraping, of course).

I will need to find out what the acronyms missing description means.

-----

ACD (Approved for CD)
ACDV (Approved for CDV)
ADISSB ()
ADTR (Approved for DTR)
ADTS (Approved for DTS)
AFDIS (Approved for FDIS)
AMW ()
ANW ()
APUB (Approved for publication)
APUBSB ()
BPUB (Being published)
BWG ()
CAN (Draft Cancelled)
CCDV (Draft circulated as CDV)
CD (Draft circulated as CD)
CDISH (Draft circulated as DISH)
CDM (CD to be discussed at meeting)
CDPAS (Draft circulated as DPAS)
CDTR (Draft circulated as DTR)
CDTS (Draft circulated as DTS)
CDVM (Rejected CDV to be discussed at meeting)
CFDIS (Draft circulated as FDIS)
DECDISH (DISH at editing check)
DECFDIS (FDIS at editing check)
DECPUB (Publication at editing check)
DEL (Deleted/abandoned)
DELPUB (Deleted publication)
DREJ ()
DTRM (Rejected DTR to be discussed at meeting)
DTSM (Rejected DTS to be discussed at meeting)
MERGED (Fragment merged)
MERGED (Publication merged with EN version)
NADIS ()
NCDV (CDV rejected)
NDTR (DTR rejected)
NDTS (DTS rejected)
NFDIS (FDIS rejected)
PCC (Preparation of CC)
PNW (New work item proposal)
PPUB (Publication issued)
PRVC (Preparation of RVC)
PRVD (Preparation of RVD)
PRVDISH (Preparation of RVDISH)
PRVDPAS (Preparation of RVDPAS)
PRVDTR (Preparation of RVDTR)
PRVDTS (Preparation of RVDTS)
PRVN (Preparation of RVN)
PWI (Preliminary work item)
RDIS ()
RDISH (DISH received and registered)
RFDIS (FDIS received and registered)
RPUB (Publication received and registered)
SPE ()
SPLIT (Project Fragmented)
SRP ()
SUSPENDED (Project Suspended)
TCDV (Translation of CDV)
TDISH (Translation of DISH)
TDTR (Translation of DTR)
TDTS (Translation of DTS)
TFDIS (Translation of FDIS)
TPUB (Translation of publication)
WPUB (Publication withdrawn)
preCD (Preparation of CD document)
preCDPAS (Preparation of DPAS)
preDISH (Preparation of DISH)
preDTR (Preparation of DTR document)
prePNW (Preparation of NP document)

**Comment by andrew2net** [comment]
@ronaldtse do we have stage and substage codes for all these statuses?
```yaml
ACD:
  status: Approved for CD
  stage: '20.99'
...
```

**Comment by andrew2net** [comment]
There are two identical abbreviations:

MERGED (Fragment merged)
MERGED (Publication merged with EN version)

The select element has identicals values for these options

**Comment by ronaldtse** [comment]
> do we have stage and substage codes for all these statuses?

I don't think so, will rely on you to investigate.

> MERGED (Fragment merged)
> MERGED (Publication merged with EN version)
> The select element has identicals values for these options

I think we just consider "merged" as the general case, we can't really tell what is merged with what.

**Comment by andrew2net** [comment]
I use this [mapping](https://github.com/metanorma/metanorma-iec/issues/5#issuecomment-526609960)
But I didn't manage to resole stage codes for some abbreviations (SPE, SPLIT, SRP, SUSPENDED, preCD, preCDPAS, preDISH, preDTR, prePNW)

**Comment by ronaldtse** [comment]
I think SPLIT is similar to on merge, it’s a relationship not a stage. preCD and preCDPAS just means not yet CD/CD for PAS. The rest I have no idea.

**Comment by ronaldtse** [comment]
@andrew2net for research reasons can you help list some examples of SPLIT and MERGED items for @strogonoff ? Thanks!

**Comment by andrew2net** [comment]
MERGED
https://www.iec.ch/dyn/www/f?p=103:38:21507695285560::::FSP_ORG_ID,FSP_APEX_PAGE,FSP_PROJECT_ID:1215,20,11672
https://www.iec.ch/dyn/www/f?p=103:38:21507695285560::::FSP_ORG_ID,FSP_APEX_PAGE,FSP_PROJECT_ID:1215,20,244
https://www.iec.ch/dyn/www/f?p=103:38:21507695285560::::FSP_ORG_ID,FSP_APEX_PAGE,FSP_PROJECT_ID:1215,20,9911
https://www.iec.ch/dyn/www/f?p=103:38:21507695285560::::FSP_ORG_ID,FSP_APEX_PAGE,FSP_PROJECT_ID:1215,20,249
https://www.iec.ch/dyn/www/f?p=103:38:21507695285560::::FSP_ORG_ID,FSP_APEX_PAGE,FSP_PROJECT_ID:1215,20,17599

SPLIT
https://webstore.iec.ch/publication/64542
https://webstore.iec.ch/publication/22643
https://webstore.iec.ch/publication/25215
https://webstore.iec.ch/publication/22635
https://webstore.iec.ch/publication/25216
https://webstore.iec.ch/publication/59839

**Comment by ronaldtse** [comment]
Ping @strogonoff here's the list you wanted.

**Comment by ronaldtse** [comment]
Thanks @andrew2net !
