### ISSUE TITLE
Correct error message when document found is a multi-part

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iec#32]
We get this message today:
```
[relaton-iec] ("IEC 62075") fetching...
[relaton-iec] WARNING: no match found online for IEC 62075:2012. The code must be exactly like it is on the standards website.
[relaton-iec] If you wanted to cite all document parts for the reference, use "IEC 62075 (all parts)".
```
However, this document is clearly a multi-part standard as per the last line.

We should update the message of "WARNING: no match found online for IEC 62075:2012. The code must be exactly like it is on the standards website." to something like:

"WARNING: IEC 62075 found as IEC 62075:2012 but also contain parts. If you wanted to cite all document parts for the reference, use "IEC 62075 (all parts)".

**Comment by andrew2net** [comment]
@ronaldtse
