### ISSUE TITLE
Unable to fetch IEC/TR

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iec#35]
This is from `mn-samples-itu/G.650.1-201803.adoc`:

```sh
[relaton-iec] ("IEC/TR 62547") fetching...
[relaton-iec] WARNING: no match found online for IEC/TR 62547. The code must be exactly like it is on the standards website.
```

**Comment by ronaldtse** [comment]
It does exist:
<img width="723" alt="Screenshot 2021-03-08 at 1 19 42 PM" src="https://user-images.githubusercontent.com/11865/110277789-f436db80-8010-11eb-8342-3f92dfd9009b.png">

**Comment by andrew2net** [comment]
@ronaldtse the [webstore.iec.ch](https://webstore.iec.ch/searchform&q=IEC%2FTR%2062547) shows documents with break space between IEC and TR (IEC TR 62547) not slash (IEC/TR 62547), so we need to use references with break space.

**Comment by ronaldtse** [comment]
Maybe "IEC/TR" is an older way of referring to the document? it is showing up in the webstore preview:
https://webstore.iec.ch/p-preview/info_iec62547%7Bed1.0%7Den.pdf

<img width="900" alt="Screenshot 2021-03-09 at 12 08 02 PM" src="https://user-images.githubusercontent.com/11865/110417212-1cd1da80-80d0-11eb-8814-4d702e94e536.png">

<img width="1042" alt="Screenshot 2021-03-09 at 12 08 42 PM" src="https://user-images.githubusercontent.com/11865/110417253-32470480-80d0-11eb-9fc2-bff4a83711f5.png">

It would be better to support this conversion.

**Comment by ronaldtse** [comment]
Thanks @andrew2net !
