### ISSUE TITLE
Retrieve individual data from relaton-data-iec

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iec#47]
Now that #45 and https://github.com/relaton/relaton-data-iec/issues/3 have been implemented we should switch relaton-iec to use the relaton-data-iec bulk data source.

**Comment by andrew2net** [comment]
@ronaldtse @opoudjis I've implemented fetching documents from the relaton-data-iec. Could you try the `feature/use_harmonised_api` branch before I merge it into the `main`?
https://github.com/relaton/relaton-iec/pull/50

**Comment by opoudjis** [comment]
How do you want me testing this, fetch IEC/PAS 62596?

**Comment by andrew2net** [comment]
@opoudjis IEC uses the "IEC PAS 62596" identifier, without a slash. They use slash to separate issuers, like IEC/IEEE, ISO/IEC etc.

**Comment by opoudjis** [comment]
Compared before and after. The new branch looks the same to me, and looks accurate.

**Comment by ronaldtse** [comment]
Thank you @opoudjis and @andrew2net , let's go with it.

**Comment by andrew2net** [comment]
merged and released
